package com.hermes.jarvis.adapter;
import android.graphics.Color;import android.graphics.Typeface;import android.graphics.BitmapFactory;import android.os.AsyncTask;import android.text.util.Linkify;import android.view.*;import android.widget.*;import androidx.annotation.NonNull;import androidx.core.content.ContextCompat;import androidx.recyclerview.widget.RecyclerView;import com.hermes.jarvis.R;import com.hermes.jarvis.model.Message;import com.hermes.jarvis.web.ImageDownloadUtil;import java.io.InputStream;import java.net.URL;import java.text.SimpleDateFormat;import java.util.*;
public class ChatAdapter extends RecyclerView.Adapter<ChatAdapter.VH>{private final List<Message> items=new ArrayList<>();private final SimpleDateFormat fmt=new SimpleDateFormat("HH:mm:ss",Locale.getDefault());
 @NonNull public VH onCreateViewHolder(@NonNull ViewGroup p,int t){return new VH(LayoutInflater.from(p.getContext()).inflate(R.layout.item_message,p,false));}
 public void onBindViewHolder(@NonNull VH h,int pos){Message m=items.get(pos);h.tvMsg.setText(m.text);h.tvTime.setText(fmt.format(new Date(m.time)));h.tvMsg.setTypeface(Typeface.MONOSPACE);h.img.setVisibility(View.GONE);h.download.setVisibility(View.GONE);if(m.imageUrl!=null&&!m.imageUrl.isEmpty()){h.img.setVisibility(View.VISIBLE);new AsyncTask<Void,Void,android.graphics.Bitmap>(){protected android.graphics.Bitmap doInBackground(Void...v){try(InputStream in=new URL(m.imageUrl).openStream()){return BitmapFactory.decodeStream(in);}catch(Exception e){return null;}}protected void onPostExecute(android.graphics.Bitmap b){if(b!=null){h.img.setImageBitmap(b);h.download.setVisibility(View.VISIBLE);h.download.setOnClickListener(v->ImageDownloadUtil.download(h.itemView.getContext(),m.imageUrl,m.text));}else h.img.setVisibility(View.GONE);}}.execute();}
  h.tvMsg.setAutoLinkMask(Linkify.WEB_URLS);h.tvMsg.setLinksClickable(true);LinearLayout.LayoutParams p=(LinearLayout.LayoutParams)h.container.getLayoutParams();switch(m.type){case Message.USER:h.container.setBackground(ContextCompat.getDrawable(h.itemView.getContext(),R.drawable.bg_msg_user));h.tvMsg.setTextColor(Color.parseColor("#EAF7FF"));h.tvTime.setTextColor(Color.parseColor("#8FB4CC"));p.gravity=Gravity.END;p.setMargins(80,4,8,4);break;case Message.TERM:h.container.setBackground(ContextCompat.getDrawable(h.itemView.getContext(),R.drawable.bg_msg_term));h.tvMsg.setTextColor(Color.parseColor("#58DFAE"));h.tvMsg.setTextSize(11);h.tvTime.setTextColor(Color.parseColor("#6F8BA1"));p.gravity=Gravity.FILL_HORIZONTAL;p.setMargins(8,4,8,4);break;case Message.ERROR:h.container.setBackground(ContextCompat.getDrawable(h.itemView.getContext(),R.drawable.bg_msg_err));h.tvMsg.setTextColor(Color.parseColor("#FF6B6B"));h.tvTime.setTextColor(Color.parseColor("#6F8BA1"));p.gravity=Gravity.FILL_HORIZONTAL;p.setMargins(8,4,8,4);break;case Message.INFO:h.container.setBackground(ContextCompat.getDrawable(h.itemView.getContext(),R.drawable.bg_msg_info));h.tvMsg.setTextColor(Color.parseColor("#6FE3FF"));h.tvTime.setTextColor(Color.parseColor("#6F8BA1"));p.gravity=Gravity.FILL_HORIZONTAL;p.setMargins(8,4,8,4);break;case Message.OK:h.container.setBackground(ContextCompat.getDrawable(h.itemView.getContext(),R.drawable.bg_msg_ok));h.tvMsg.setTextColor(Color.parseColor("#58DFAE"));h.tvTime.setTextColor(Color.parseColor("#6F8BA1"));p.gravity=Gravity.FILL_HORIZONTAL;p.setMargins(8,4,8,4);break;default:h.container.setBackground(ContextCompat.getDrawable(h.itemView.getContext(),R.drawable.bg_msg_bot));h.tvMsg.setTextColor(Color.parseColor("#EAF7FF"));h.tvTime.setTextColor(Color.parseColor("#6F8BA1"));p.gravity=Gravity.START;p.setMargins(8,4,80,4);}
  h.container.setLayoutParams(p);}
 public int getItemCount(){return items.size();}public void add(Message m){items.add(m);notifyItemInserted(items.size()-1);}public void clear(){items.clear();notifyDataSetChanged();}
 static class VH extends RecyclerView.ViewHolder{LinearLayout container;TextView tvMsg,tvTime;ImageView img;Button download;VH(@NonNull View v){super(v);container=v.findViewById(R.id.messageContainer);tvMsg=v.findViewById(R.id.tvMessage);tvTime=v.findViewById(R.id.tvTime);img=v.findViewById(R.id.messageImage);download=v.findViewById(R.id.btnDownloadImage);}}
}
