package com.hermes.jarvis.service;

import android.app.*;import android.content.*;import android.os.*;import androidx.core.app.NotificationCompat;import com.google.gson.*;import com.hermes.jarvis.ai.*;import com.hermes.jarvis.core.MemoryBank;import com.hermes.jarvis.utils.PrefsManager;import java.io.IOException;import java.util.concurrent.*;import okhttp3.*;

/** Lightweight Telegram long-poll agent. Allowlist is enforced before AI processing. */
public class TelegramAgentService extends Service {
    private final ScheduledExecutorService exec=Executors.newSingleThreadScheduledExecutor(); private long offset=0; private OkHttpClient client; private PrefsManager prefs; private AIManager ai;
    public int onStartCommand(Intent i,int flags,int id){startForeground(42,notification());poll();return START_STICKY;}
    public void onCreate(){super.onCreate();prefs=new PrefsManager(this);client=new OkHttpClient();ai=new AIManager(this,new MemoryBank(this));}
    private Notification notification(){String ch="jarvis_tg";if(Build.VERSION.SDK_INT>=26)((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).createNotificationChannel(new NotificationChannel(ch,"JARVIS Telegram",NotificationManager.IMPORTANCE_LOW));return new NotificationCompat.Builder(this,ch).setSmallIcon(com.hermes.jarvis.R.mipmap.ic_launcher).setContentTitle("JARVIS Telegram Agent").setContentText("Allowlist protected").setOngoing(true).build();}
    private void poll(){exec.schedule(this::fetch,100,TimeUnit.MILLISECONDS);}
    private void fetch(){String token=prefs.telegramToken();if(token.isEmpty()){poll();return;}Request r=new Request.Builder().url("https://api.telegram.org/bot"+token+"/getUpdates?timeout=20&offset="+offset).build();client.newCall(r).enqueue(new Callback(){public void onFailure(Call c,IOException e){poll();}public void onResponse(Call c,Response x)throws IOException{try(x){String raw=x.body()==null?"":x.body().string();JsonObject o=JsonParser.parseString(raw).getAsJsonObject();if(o.has("result"))for(JsonElement e:o.getAsJsonArray("result")){JsonObject u=e.getAsJsonObject();offset=Math.max(offset,u.get("update_id").getAsLong()+1);JsonObject m=u.getAsJsonObject("message");if(m==null||!m.has("text"))continue;String chat=m.getAsJsonObject("chat").get("id").getAsString();if(!allowed(chat))continue;String text=m.get("text").getAsString();ai.send(text,null,new AIManager.Callback(){public void onResponse(AIResponse a){send(chat,a.message);}public void onError(String e){send(chat,"❌ "+e);}});} }catch(Exception ignored){}finally{poll();}}});}
    private boolean allowed(String id){String raw=prefs.telegramAllowlist();if(raw.isEmpty())return false;for(String x:raw.split(","))if(x.trim().equals(id))return true;return false;}
    private void send(String chat,String text){final String finalText=text==null?"":text;RequestBody b=RequestBody.create(new Gson().toJson(new java.util.HashMap<String,String>(){{put("chat_id",chat);put("text",finalText);}}),MediaType.parse("application/json"));Request r=new Request.Builder().url("https://api.telegram.org/bot"+prefs.telegramToken()+"/sendMessage").post(b).build();client.newCall(r).enqueue(new Callback(){public void onFailure(Call c,IOException e){}public void onResponse(Call c,Response x)throws IOException{x.close();}});}
    public void onDestroy(){exec.shutdownNow();super.onDestroy();} public android.os.IBinder onBind(Intent i){return null;}
}
